SELECT * FROM EMP
SELECT * FROM DEPT
--1.查询部门名称是‘SALES’的员工信息 
SELECT EMP.*
FROM EMP INNER JOIN DEPT ON EMP.DEPTNO =DEPT.DEPTNO
AND DNAME='SALES'

--2.查询公司中薪水最高的员工信息 
SELECT *
FROM EMP 
WHERE SAL=(SELECT MAX(SAL) FROM EMP)


--3.查询各部门中最高薪水的员工编号，姓名… 
SELECT EMPNO,ENAME,SAL,DEPTNO
FROM EMP
WHERE SAL IN (SELECT MAX(SAL)FROM EMP GROUP BY DEPTNO )


--4.查询各部门最高薪水的员工信息 
SELECT *
from EMP
WHERE SAL IN (SELECT  MAX(SAL) FROM EMP GROUP BY DEPTNO)

--5.查询薪水大于该部门平均薪水的员工信息 
SELECT *
FROM EMP
WHERE ENAME IN (SELECT ENAME FROM EMP WHERE SAL>(SELECT AVG(SAL)FROM EMP WHERE DEPTNO=10) AND DEPTNO=10)
OR  ENAME IN(SELECT ENAME FROM EMP WHERE SAL>(SELECT AVG(SAL)FROM EMP WHERE DEPTNO=20) AND DEPTNO=20)
OR ENAME IN   (SELECT ENAME FROM EMP WHERE SAL>(SELECT AVG(SAL)FROM EMP WHERE DEPTNO=30) AND DEPTNO=30)
OR ENAME IN  (SELECT ENAME FROM EMP WHERE SAL>(SELECT AVG(SAL)FROM EMP WHERE DEPTNO=40) AND DEPTNO=40)

--6.查询部门名称是‘SALES’的员工信息 
SELECT *
FROM EMP INNER JOIN DEPT ON EMP.DEPTNO=DEPT.DEPTNO
AND DNAME='SALES'


--7.查询领导者是‘BLAKE’的员工信息 
SELECT *
FROM EMP
WHERE MGR = (SELECT EMPNO FROM EMP WHERE ENAME='BLAKE' )

--8.查询和SMITH工作相同的员工信息 
SELECT *
FROM EMP
WHERE JOB =(SELECT JOB FROM EMP WHERE ENAME='SMITH')

--9.查询平均工资比10部门低的部门编号 
SELECT DEPTNO
FROM EMP 
GROUP BY DEPTNO
HAVING AVG(SAL)<(SELECT AVG(SAL) FROM EMP WHERE DEPTNO=10)

--10.查询在NEW YORK工作的所有员工
SELECT *
FROM EMP INNER JOIN DEPT ON EMP.DEPTNO=DEPT.DEPTNO
AND LOC='NEW YORK' 

--11.查询10号部门的员工在整个公司中所占的比例：
SELECT (SELECT COUNT(*)FROM EMP WHERE DEPTNO=10)*100/ COUNT(*) AS '百分比'
FROM EMP
 

--12、查询比普通员工的最高薪水还要高的领导者姓名
SELECT ENAME , SAL
FROM EMP
WHERE (SELECT MAX(SAL) FROM EMP WHERE EMPNO NOT IN (SELECT MGR FROM EMP WHERE MGR IS NOT NULL) ) <
			ANY  (SELECT SAL FROM EMP WHERE EMPNO IN (SELECT MGR FROM EMP)) AND EMPNO IN (SELECT MGR FROM EMP)

--13、找出薪水最高的五个人 
SELECT  TOP 5 *
FROM EMP 
ORDER BY SAL DESC

--14、列出至少有三个员工的所有部门和部门信息
SELECT DEPT.DEPTNO,DEPT.DNAME,DEPT.LOC
FROM EMP INNER JOIN DEPT ON  EMP.DEPTNO = DEPT.DEPTNO
GROUP BY DEPT.DEPTNO,DEPT.DNAME,DEPT.LOC
HAVING COUNT(*)>=3

--15、查询最后入职的5名员工
SELECT  TOP 5 *
FROM EMP
ORDER BY HIREDATE DESC

--16、列出最低薪金大于1500的各种工作以及从事此工作的全部雇员人数
SELECT JOB ,COUNT(*)
FROM EMP
GROUP BY JOB
HAVING MIN(SAL)>1500 

--17、列出各种工作的最低工资以及从事该工作的雇员姓名
SELECT *
FROM EMP
WHERE ENAME IN (SELECT ENAME FROM EMP WHERE SAL IN(SELECT MIN(SAL) FROM EMP GROUP BY JOB))

--18、求薪水最低的部门经理所在部门的名称
SELECT DEPT.DNAME
FROM EMP INNER JOIN DEPT ON EMP.DEPTNO=DEPT.DEPTNO
WHERE ENAME=(SELECT ENAME FROM EMP WHERE SAL=(SELECT MIN(SAL)FROM EMP WHERE JOB='MANAGER'))
