1.查询部门名称是‘SALES’的员工信息 
SELECT * FROM EMP e INNER JOIN DEPT d
	ON e.DEPTNO = d.DEPTNO
	AND d.DNAME = 'SALES';
	
2.查询公司中薪水最高的员工信息
SELECT * FROM EMP 
WHERE SAL = (SELECT MAX(SAL) FROM EMP);

3.查询各部门中最高薪水的员工编号，姓名…
SELECT e.EMPNO,e.ENAME FROM EMP e
WHERE e.SAL IN (SELECT MAX(e.SAL) FROM EMP e GROUP BY e.DEPTNO);

4.查询各部门最高薪水的员工信息 
SELECT * FROM EMP e
WHERE e.SAL IN (SELECT MAX(e.SAL) FROM EMP e GROUP BY e.DEPTNO);

5.查询薪水大于该部门平均薪水的员工信息
SELECT * FROM EMP e WHERE e.SAL > (SELECT AVG(e.SAL) FROM EMP e WHERE e.DEPTNO = 10) AND e.DEPTNO = 10
						OR e.SAL >(SELECT AVG(e.SAL) FROM EMP e WHERE e.DEPTNO = 20) AND e.DEPTNO=20
						OR e.SAL >(SELECT AVG(e.SAL) FROM EMP e WHERE e.DEPTNO = 30) AND e.DEPTNO=30
						OR e.SAL >(SELECT AVG(e.SAL) FROM EMP e WHERE e.DEPTNO = 40) AND e.DEPTNO=40
ORDER BY e.DEPTNO;

6.查询部门名称是‘SALES’的员工信息 
SELECT * FROM EMP e INNER JOIN DEPT d
	ON e.DEPTNO = d.DEPTNO
	AND d.DNAME = 'SALES';

7.查询领导者是‘BLAKE’的员工信息
SELECT * FROM EMP e
WHERE e.MGR=(SELECT e.EMPNO FROM EMP e WHERE e.ENAME = 'BLAKE');

8.查询和SMITH工作相同的员工信息
SELECT * FROM EMP e
WHERE e.JOB = (SELECT E.JOB FROM EMP e WHERE e.ENAME = 'SMITH');

9.查询平均工资比10部门低的部门编号
SELECT e.DEPTNO FROM EMP e 
GROUP BY e.DEPTNO 
HAVING AVG(e.SAL)<(SELECT AVG(e.SAL) FROM EMP e WHERE e.DEPTNO = 10);
 

10.查询在NEW YORK工作的所有员工 
SELECT e.* FROM EMP e INNER JOIN DEPT d ON d.DEPTNO = e.DEPTNO
AND d.LOC = 'NEW YORK';

11.查询10号部门的员工在整个公司中所占的比例： 
SELECT (SELECT COUNT(e.EMPNO) FROM EMP e WHERE e.DEPTNO = 10)*100/(COUNT(e.EMPNO)) AS '比例(%)' FROM EMP e;

12、查询比普通员工的最高薪水还要高的领导者姓名
SELECT e.ENAME FROM EMP e
WHERE e.SAL >(SELECT MAX(e.SAL) FROM EMP e 
WHERE e.EMPNO NOT IN (SELECT e.EMPNO FROM EMP e WHERE e.EMPNO IN(SELECT e.MGR FROM EMP e)));

13、找出薪水最高的五个人
SELECT TOP 5 * FROM EMP e
ORDER BY e.SAL DESC;

14、列出至少有三个员工的所有部门和部门信息
SELECT d.* FROM EMP e INNER JOIN DEPT d ON d.DEPTNO = e.DEPTNO
GROUP BY e.DEPTNO,d.DEPTNO,d.DNAME,d.LOC 
HAVING COUNT(e.EMPNO)>=3;

15、查询最后入职的5名员工
SELECT TOP 5 e.ENAME  FROM EMP e
ORDER BY e.HIREDATE DESC;

16、列出最低薪金大于1500的各种工作以及从事此工作的全部雇员人数
SELECT e.JOB AS '职位',COUNT(e.EMPNO) AS '人数' FROM EMP e 
GROUP BY e.JOB
HAVING MIN(e.SAL)>1500;

17、列出各种工作的最低工资以及从事该工作的雇员姓名
SELECT e.ENAME FROM EMP e 
WHERE e.SAL IN (SELECT MIN(e.SAL) FROM EMP e GROUP BY e.JOB);

18、求薪水最低的部门经理所在部门的名称
SELECT d.DNAME FROM EMP e INNER JOIN DEPT d ON d.DEPTNO = e.DEPTNO
AND e.SAL = (SELECT MIN(e.SAL) FROM EMP e WHERE e.EMPNO IN (SELECT e.MGR FROM EMP e GROUP BY e.MGR));