--三、用SQL语句完成如下操作 (70分)
--1.	查询姓“李”的老师的名字
SELECT TNAME
FROM TEACHER 
WHERE TNAME LIKE '李%'

--2.	查询男生、女生分别有多少人
SELECT SSEX, COUNT(*)
FROM STUDENT 
GROUP BY SSEX

--3.	查询学生中第二个字是文的有哪些人
SELECT SNAME
FROM STUDENT 
WHERE SNAME LIKE '_文%'

--4.	查询语文考试的最高分、最低分以及平均分
SELECT MAX(SC.SCORE),MIN(SC.SCORE),AVG(SC.SCORE)
FROM COURSE C INNER JOIN SC SC ON C.CID = SC. CID
WHERE C.CNAME ='语文'

--5.	查询平均成绩大于60分的同学的学号和平均成绩；
SELECT ST.SID,AVG(SC.SCORE)
FROM student ST INNER JOIN SC SC ON ST.SID=SC.SID
GROUP BY ST.SID 
HAVING AVG(SC.SCORE)>60

--6.	查询所有同学的学号、姓名、选课数、总成绩；
SELECT S.SID , S.SNAME,COUNT(*),SUM(SC.SCORE)
FROM student S INNER JOIN SC SC ON S.SID=SC.SID
GROUP BY S.SID,S.SNAME

--7.	查询网络营销这门课的教师名称、学生名称、学生成绩
SELECT T.TNAME,S.SNAME,SC.SCORE
FROM student S INNER JOIN SC SC ON SC.SID=S.SID
	INNER JOIN COURSE C ON C.CID=SC.CID
	INNER JOIN TEACHER T ON T.TID=C.TID
	AND C.CNAME ='网络营销'
	
--8.	查询所有课程成绩小于80分的同学的学号、姓名；
SELECT DISTINCT S.SID,S.SNAME
FROM STUDENT S INNER JOIN SC SC ON S.SID = SC.SID
	AND SC.SCORE <80
	
--9.	查询没有参加所有课程考试的同学的学号、姓名
SELECT S.SID , S.SNAME
FROM STUDENT S LEFT JOIN SC SC ON S.SID=SC.SID
AND SC.SCORE IS NULL

--10.	把“SC”表中“苏轼”老师教的课的成绩都减5分；
UPDATE SC SET SCORE =SCORE-5 WHERE CID=(
	SELECT CID FROM COURSE C INNER JOIN TEACHER T ON C.TID=T.TID AND TNAME ='苏轼'
)
--11.	删除成绩表中“李清照”老师教的课程的记录；
DELETE SC WHERE CID=(
	SELECT CID FROM COURSE C INNER JOIN TEACHER T ON C.TID=T.TID AND T.TNAME='李清照' 
)

--12.	查询语文的最高分以及学生姓名
SELECT TOP 1 SC.SCORE,S.SNAME 
FROM STUDENT S INNER JOIN SC SC ON S.SID = SC.SID 
	INNER JOIN COURSE C ON C.CID=SC.CID
	AND C.CNAME='语文'
	ORDER BY SC.SCORE DESC
	
--13.	查询每门科目的平均成绩
SELECT SC.CID, AVG(SC.SCORE)
FROM STUDENT S INNER JOIN SC SC ON S.SID =SC.SID
	GROUP BY SC.CID
	
--14.	查询每门科目的及格率
SELECT SC.CID, COUNT(*)*100/(SELECT COUNT(*)FROM STUDENT ST INNER JOIN SC SC1 ON ST.SID=SC1.SID AND SC.CID=SC1.CID GROUP BY CID) AS'及格百分比'
FROM STUDENT S INNER JOIN SC SC ON S.SID=SC.SID
AND SC.SCORE>=60
GROUP BY SC.CID

--15.	查询英语前三名的学生姓名、分数、教师名称
SELECT TOP 3 S.SNAME,SC.SCORE,T.TNAME
FROM student S INNER JOIN SC SC ON S.SID=SC.SID
	INNER JOIN COURSE  C ON C.CID=SC.CID
	INNER JOIN TEACHER T ON T.TID=C.TID
	AND C.CNAME ='英语'
	ORDER BY SC. SCORE DESC
	
--16.	查询每门课考试的人数
SELECT CID, COUNT(*)
FROM SC
WHERE SCORE IS NOT NULL
GROUP BY CID

--17.	查询平均成绩大于85的所有学生的学号、姓名和平均成绩
SELECT S.SID,S.SNAME,AVG(SC.SCORE)
FROM STUDENT S INNER JOIN SC SC ON S.SID=SC.SID	
GROUP BY S.SID,S.SNAME
HAVING AVG(SC.SCORE)>85

--18.	查询相同年龄且相同性别的有哪些人
SELECT S.SNAME,ST.SNAME
FROM student S,student ST
WHERE S.SAGE=(SELECT ST.SAGE FROM student ST WHERE S.SID!=ST.SID )
AND S.SSEX=(SELECT STU.SSEX FROM student STU WHERE S.SID!=STU.SID)

--19.	查询java基础大于等于70且小于等于90的女生，输出姓名、性别、分数
SELECT S.SNAME,S.SSEX,SC.SCORE
FROM STUDENT S INNER JOIN SC SC ON S.SID=SC.SID
	INNER JOIN COURSE C ON C.CID=SC.CID
	AND C.CNAME='java基础'
	AND SC.SCORE BETWEEN 10 AND 90
	AND S.SSEX='女'
	
--20.	查询苏轼老师教的课中，成绩最好的前两名，输出名字和分数
SELECT DISTINCT TOP 2 S.SNAME,SC.SCORE
FROM STUDENT S INNER JOIN SC SC ON S.SID = SC.SID
	INNER JOIN COURSE C ON C.CID=SC.CID
	INNER JOIN TEACHER T ON T.TID=C.TID
	AND T.TNAME='苏轼'
	ORDER BY SC.SCORE DESC

