select *from studentscore;
insert into studentscore(sid,name) select sID,sname from students ;
select *from studentscore;
update studentscore set yuwenscore=85,mathscore=90,english=80 where sid=1;
update studentscore set yuwenscore=85.5,mathscore=91,english=88 where sid=2;
update studentscore set yuwenscore=85,mathscore=78,english=88 where sid=3;
update studentscore set yuwenscore=87,mathscore=89,english=82 where sid=4;
update studentscore set yuwenscore=85,mathscore=90,english=80 where sid=5;
update studentscore set yuwenscore=86,mathscore=90,english=80 where sid=6;
update studentscore set yuwenscore=85,mathscore=90,english=80 where sid=7;
update studentscore set yuwenscore=85,mathscore=90,english=80 where sid=8;
update studentscore set yuwenscore=81,mathscore=90,english=80 where sid=9;
update studentscore set yuwenscore=82,mathscore=90,english=80 where sid=10;
update studentscore set yuwenscore=83,mathscore=90,english=80 where sid=11;
update studentscore set yuwenscore=84,mathscore=90,english=80 where sid=12;
update studentscore set yuwenscore=85,mathscore=90,english=80 where sid=13;
update studentscore set yuwenscore=82.5,mathscore=90,english=80 where sid=14;
update studentscore set yuwenscore=88,mathscore=90,english=80 where sid=15;
update studentscore set yuwenscore=90,mathscore=90,english=80 where sid=16;
update studentscore set yuwenscore=91,mathscore=90,english=80 where sid=17;
update studentscore set yuwenscore=85,mathscore=90,english=80 where sid=18;
update studentscore set yuwenscore=98,mathscore=90,english=80 where sid=19;
update studentscore set yuwenscore=97,mathscore=90,english=80 where sid=20;
update studentscore set yuwenscore=83,mathscore=90,english=80 where sid=21;
update studentscore set yuwenscore=80,mathscore=90,english=80 where sid=22;
select *from studentscore;